#ifndef _INTERRUPT_REG_H
#define _INTERRUPT_REG_H

#include <platform.h>

#define EIBD0                  (*(volatile unsigned long  *)0xFFFEEB00)
#define EIBD1                  (*(volatile unsigned long  *)0xFFFEEB04)
#define EIBD2                  (*(volatile unsigned long  *)0xFFFEEB08)
#define EIBD3                  (*(volatile unsigned long  *)0xFFFEEB0C)
#define EIBD4                  (*(volatile unsigned long  *)0xFFFEEB10)
#define EIBD5                  (*(volatile unsigned long  *)0xFFFEEB14)
#define EIBD6                  (*(volatile unsigned long  *)0xFFFEEB18)
#define EIBD7                  (*(volatile unsigned long  *)0xFFFEEB1C)
#define EIBD8                  (*(volatile unsigned long  *)0xFFFEEB20)
#define EIBD9                  (*(volatile unsigned long  *)0xFFFEEB24)
#define EIBD10                 (*(volatile unsigned long  *)0xFFFEEB28)
#define EIBD11                 (*(volatile unsigned long  *)0xFFFEEB2C)
#define EIBD12                 (*(volatile unsigned long  *)0xFFFEEB30)
#define EIBD13                 (*(volatile unsigned long  *)0xFFFEEB34)
#define EIBD14                 (*(volatile unsigned long  *)0xFFFEEB38)
#define EIBD15                 (*(volatile unsigned long  *)0xFFFEEB3C)
#define EIBD16                 (*(volatile unsigned long  *)0xFFFEEB40)
#define EIBD17                 (*(volatile unsigned long  *)0xFFFEEB44)
#define EIBD18                 (*(volatile unsigned long  *)0xFFFEEB48)
#define EIBD19                 (*(volatile unsigned long  *)0xFFFEEB4C)
#define EIBD20                 (*(volatile unsigned long  *)0xFFFEEB50)
#define EIBD21                 (*(volatile unsigned long  *)0xFFFEEB54)
#define EIBD22                 (*(volatile unsigned long  *)0xFFFEEB58)
#define EIBD23                 (*(volatile unsigned long  *)0xFFFEEB5C)
#define EIBD24                 (*(volatile unsigned long  *)0xFFFEEB60)
#define EIBD25                 (*(volatile unsigned long  *)0xFFFEEB64)
#define EIBD26                 (*(volatile unsigned long  *)0xFFFEEB68)
#define EIBD27                 (*(volatile unsigned long  *)0xFFFEEB6C)
#define EIBD28                 (*(volatile unsigned long  *)0xFFFEEB70)
#define EIBD29                 (*(volatile unsigned long  *)0xFFFEEB74)
#define EIBD30                 (*(volatile unsigned long  *)0xFFFEEB78)
#define EIBD31                 (*(volatile unsigned long  *)0xFFFEEB7C)
#define EIBD32                 (*(volatile unsigned long  *)0xFFFFB880)
#define EIBD33                 (*(volatile unsigned long  *)0xFFFFB884)
#define EIBD34                 (*(volatile unsigned long  *)0xFFFFB888)
#define EIBD35                 (*(volatile unsigned long  *)0xFFFFB88C)
#define EIBD36                 (*(volatile unsigned long  *)0xFFFFB890)
#define EIBD37                 (*(volatile unsigned long  *)0xFFFFB894)
#define EIBD38                 (*(volatile unsigned long  *)0xFFFFB898)
#define EIBD39                 (*(volatile unsigned long  *)0xFFFFB89C)
#define EIBD40                 (*(volatile unsigned long  *)0xFFFFB8A0)
#define EIBD41                 (*(volatile unsigned long  *)0xFFFFB8A4)
#define EIBD42                 (*(volatile unsigned long  *)0xFFFFB8A8)
#define EIBD43                 (*(volatile unsigned long  *)0xFFFFB8AC)
#define EIBD44                 (*(volatile unsigned long  *)0xFFFFB8B0)
#define EIBD45                 (*(volatile unsigned long  *)0xFFFFB8B4)
#define EIBD46                 (*(volatile unsigned long  *)0xFFFFB8B8)
#define EIBD47                 (*(volatile unsigned long  *)0xFFFFB8BC)
#define EIBD48                 (*(volatile unsigned long  *)0xFFFFB8C0)
#define EIBD49                 (*(volatile unsigned long  *)0xFFFFB8C4)
#define EIBD50                 (*(volatile unsigned long  *)0xFFFFB8C8)
#define EIBD51                 (*(volatile unsigned long  *)0xFFFFB8CC)
#define EIBD52                 (*(volatile unsigned long  *)0xFFFFB8D0)
#define EIBD53                 (*(volatile unsigned long  *)0xFFFFB8D4)
#define EIBD54                 (*(volatile unsigned long  *)0xFFFFB8D8)
#define EIBD55                 (*(volatile unsigned long  *)0xFFFFB8DC)
#define EIBD56                 (*(volatile unsigned long  *)0xFFFFB8E0)
#define EIBD57                 (*(volatile unsigned long  *)0xFFFFB8E4)
#define EIBD58                 (*(volatile unsigned long  *)0xFFFFB8E8)
#define EIBD59                 (*(volatile unsigned long  *)0xFFFFB8EC)
#define EIBD60                 (*(volatile unsigned long  *)0xFFFFB8F0)
#define EIBD61                 (*(volatile unsigned long  *)0xFFFFB8F4)
#define EIBD62                 (*(volatile unsigned long  *)0xFFFFB8F8)
#define EIBD63                 (*(volatile unsigned long  *)0xFFFFB8FC)
#define EIBD64                 (*(volatile unsigned long  *)0xFFFFB900)
#define EIBD65                 (*(volatile unsigned long  *)0xFFFFB904)
#define EIBD66                 (*(volatile unsigned long  *)0xFFFFB908)
#define EIBD67                 (*(volatile unsigned long  *)0xFFFFB90C)
#define EIBD68                 (*(volatile unsigned long  *)0xFFFFB910)
#define EIBD69                 (*(volatile unsigned long  *)0xFFFFB914)
#define EIBD70                 (*(volatile unsigned long  *)0xFFFFB918)
#define EIBD71                 (*(volatile unsigned long  *)0xFFFFB91C)
#define EIBD72                 (*(volatile unsigned long  *)0xFFFFB920)
#define EIBD73                 (*(volatile unsigned long  *)0xFFFFB924)
#define EIBD74                 (*(volatile unsigned long  *)0xFFFFB928)
#define EIBD75                 (*(volatile unsigned long  *)0xFFFFB92C)
#define EIBD76                 (*(volatile unsigned long  *)0xFFFFB930)
#define EIBD77                 (*(volatile unsigned long  *)0xFFFFB934)
#define EIBD78                 (*(volatile unsigned long  *)0xFFFFB938)
#define EIBD79                 (*(volatile unsigned long  *)0xFFFFB93C)
#define EIBD80                 (*(volatile unsigned long  *)0xFFFFB940)
#define EIBD81                 (*(volatile unsigned long  *)0xFFFFB944)
#define EIBD82                 (*(volatile unsigned long  *)0xFFFFB948)
#define EIBD83                 (*(volatile unsigned long  *)0xFFFFB94C)
#define EIBD84                 (*(volatile unsigned long  *)0xFFFFB950)
#define EIBD85                 (*(volatile unsigned long  *)0xFFFFB954)
#define EIBD86                 (*(volatile unsigned long  *)0xFFFFB958)
#define EIBD87                 (*(volatile unsigned long  *)0xFFFFB95C)
#define EIBD88                 (*(volatile unsigned long  *)0xFFFFB960)
#define EIBD89                 (*(volatile unsigned long  *)0xFFFFB964)
#define EIBD90                 (*(volatile unsigned long  *)0xFFFFB968)
#define EIBD91                 (*(volatile unsigned long  *)0xFFFFB96C)
#define EIBD92                 (*(volatile unsigned long  *)0xFFFFB970)
#define EIBD93                 (*(volatile unsigned long  *)0xFFFFB974)
#define EIBD94                 (*(volatile unsigned long  *)0xFFFFB978)
#define EIBD95                 (*(volatile unsigned long  *)0xFFFFB97C)
#define EIBD96                 (*(volatile unsigned long  *)0xFFFFB980)
#define EIBD97                 (*(volatile unsigned long  *)0xFFFFB984)
#define EIBD98                 (*(volatile unsigned long  *)0xFFFFB988)
#define EIBD99                 (*(volatile unsigned long  *)0xFFFFB98C)
#define EIBD100                (*(volatile unsigned long  *)0xFFFFB990)
#define EIBD101                (*(volatile unsigned long  *)0xFFFFB994)
#define EIBD102                (*(volatile unsigned long  *)0xFFFFB998)
#define EIBD103                (*(volatile unsigned long  *)0xFFFFB99C)
#define EIBD104                (*(volatile unsigned long  *)0xFFFFB9A0)
#define EIBD105                (*(volatile unsigned long  *)0xFFFFB9A4)
#define EIBD106                (*(volatile unsigned long  *)0xFFFFB9A8)
#define EIBD107                (*(volatile unsigned long  *)0xFFFFB9AC)
#define EIBD108                (*(volatile unsigned long  *)0xFFFFB9B0)
#define EIBD109                (*(volatile unsigned long  *)0xFFFFB9B4)
#define EIBD110                (*(volatile unsigned long  *)0xFFFFB9B8)
#define EIBD111                (*(volatile unsigned long  *)0xFFFFB9BC)
#define EIBD112                (*(volatile unsigned long  *)0xFFFFB9C0)
#define EIBD113                (*(volatile unsigned long  *)0xFFFFB9C4)
#define EIBD114                (*(volatile unsigned long  *)0xFFFFB9C8)
#define EIBD115                (*(volatile unsigned long  *)0xFFFFB9CC)
#define EIBD116                (*(volatile unsigned long  *)0xFFFFB9D0)
#define EIBD117                (*(volatile unsigned long  *)0xFFFFB9D4)
#define EIBD118                (*(volatile unsigned long  *)0xFFFFB9D8)
#define EIBD119                (*(volatile unsigned long  *)0xFFFFB9DC)
#define EIBD120                (*(volatile unsigned long  *)0xFFFFB9E0)
#define EIBD121                (*(volatile unsigned long  *)0xFFFFB9E4)
#define EIBD122                (*(volatile unsigned long  *)0xFFFFB9E8)
#define EIBD123                (*(volatile unsigned long  *)0xFFFFB9EC)
#define EIBD124                (*(volatile unsigned long  *)0xFFFFB9F0)
#define EIBD125                (*(volatile unsigned long  *)0xFFFFB9F4)
#define EIBD126                (*(volatile unsigned long  *)0xFFFFB9F8)
#define EIBD127                (*(volatile unsigned long  *)0xFFFFB9FC)
#define EIBD128                (*(volatile unsigned long  *)0xFFFFBA00)
#define EIBD129                (*(volatile unsigned long  *)0xFFFFBA04)
#define EIBD130                (*(volatile unsigned long  *)0xFFFFBA08)
#define EIBD131                (*(volatile unsigned long  *)0xFFFFBA0C)
#define EIBD132                (*(volatile unsigned long  *)0xFFFFBA10)
#define EIBD133                (*(volatile unsigned long  *)0xFFFFBA14)
#define EIBD134                (*(volatile unsigned long  *)0xFFFFBA18)
#define EIBD135                (*(volatile unsigned long  *)0xFFFFBA1C)
#define EIBD136                (*(volatile unsigned long  *)0xFFFFBA20)
#define EIBD137                (*(volatile unsigned long  *)0xFFFFBA24)
#define EIBD138                (*(volatile unsigned long  *)0xFFFFBA28)
#define EIBD139                (*(volatile unsigned long  *)0xFFFFBA2C)
#define EIBD140                (*(volatile unsigned long  *)0xFFFFBA30)
#define EIBD141                (*(volatile unsigned long  *)0xFFFFBA34)
#define EIBD142                (*(volatile unsigned long  *)0xFFFFBA38)
#define EIBD143                (*(volatile unsigned long  *)0xFFFFBA3C)
#define EIBD144                (*(volatile unsigned long  *)0xFFFFBA40)
#define EIBD145                (*(volatile unsigned long  *)0xFFFFBA44)
#define EIBD146                (*(volatile unsigned long  *)0xFFFFBA48)
#define EIBD147                (*(volatile unsigned long  *)0xFFFFBA4C)
#define EIBD148                (*(volatile unsigned long  *)0xFFFFBA50)
#define EIBD149                (*(volatile unsigned long  *)0xFFFFBA54)
#define EIBD150                (*(volatile unsigned long  *)0xFFFFBA58)
#define EIBD151                (*(volatile unsigned long  *)0xFFFFBA5C)
#define EIBD152                (*(volatile unsigned long  *)0xFFFFBA60)
#define EIBD153                (*(volatile unsigned long  *)0xFFFFBA64)
#define EIBD154                (*(volatile unsigned long  *)0xFFFFBA68)
#define EIBD155                (*(volatile unsigned long  *)0xFFFFBA6C)
#define EIBD156                (*(volatile unsigned long  *)0xFFFFBA70)
#define EIBD157                (*(volatile unsigned long  *)0xFFFFBA74)
#define EIBD158                (*(volatile unsigned long  *)0xFFFFBA78)
#define EIBD159                (*(volatile unsigned long  *)0xFFFFBA7C)
#define EIBD160                (*(volatile unsigned long  *)0xFFFFBA80)
#define EIBD161                (*(volatile unsigned long  *)0xFFFFBA84)
#define EIBD162                (*(volatile unsigned long  *)0xFFFFBA88)
#define EIBD163                (*(volatile unsigned long  *)0xFFFFBA8C)
#define EIBD164                (*(volatile unsigned long  *)0xFFFFBA90)
#define EIBD165                (*(volatile unsigned long  *)0xFFFFBA94)
#define EIBD166                (*(volatile unsigned long  *)0xFFFFBA98)
#define EIBD167                (*(volatile unsigned long  *)0xFFFFBA9C)
#define EIBD168                (*(volatile unsigned long  *)0xFFFFBAA0)
#define EIBD169                (*(volatile unsigned long  *)0xFFFFBAA4)
#define EIBD170                (*(volatile unsigned long  *)0xFFFFBAA8)
#define EIBD171                (*(volatile unsigned long  *)0xFFFFBAAC)
#define EIBD172                (*(volatile unsigned long  *)0xFFFFBAB0)
#define EIBD173                (*(volatile unsigned long  *)0xFFFFBAB4)
#define EIBD174                (*(volatile unsigned long  *)0xFFFFBAB8)
#define EIBD175                (*(volatile unsigned long  *)0xFFFFBABC)
#define EIBD176                (*(volatile unsigned long  *)0xFFFFBAC0)
#define EIBD177                (*(volatile unsigned long  *)0xFFFFBAC4)
#define EIBD178                (*(volatile unsigned long  *)0xFFFFBAC8)
#define EIBD179                (*(volatile unsigned long  *)0xFFFFBACC)
#define EIBD180                (*(volatile unsigned long  *)0xFFFFBAD0)
#define EIBD181                (*(volatile unsigned long  *)0xFFFFBAD4)
#define EIBD182                (*(volatile unsigned long  *)0xFFFFBAD8)
#define EIBD183                (*(volatile unsigned long  *)0xFFFFBADC)
#define EIBD184                (*(volatile unsigned long  *)0xFFFFBAE0)
#define EIBD185                (*(volatile unsigned long  *)0xFFFFBAE4)
#define EIBD186                (*(volatile unsigned long  *)0xFFFFBAE8)
#define EIBD187                (*(volatile unsigned long  *)0xFFFFBAEC)
#define EIBD188                (*(volatile unsigned long  *)0xFFFFBAF0)
#define EIBD189                (*(volatile unsigned long  *)0xFFFFBAF4)
#define EIBD190                (*(volatile unsigned long  *)0xFFFFBAF8)
#define EIBD191                (*(volatile unsigned long  *)0xFFFFBAFC)
#define EIBD192                (*(volatile unsigned long  *)0xFFFFBB00)
#define EIBD193                (*(volatile unsigned long  *)0xFFFFBB04)
#define EIBD194                (*(volatile unsigned long  *)0xFFFFBB08)
#define EIBD195                (*(volatile unsigned long  *)0xFFFFBB0C)
#define EIBD196                (*(volatile unsigned long  *)0xFFFFBB10)
#define EIBD197                (*(volatile unsigned long  *)0xFFFFBB14)
#define EIBD198                (*(volatile unsigned long  *)0xFFFFBB18)
#define EIBD199                (*(volatile unsigned long  *)0xFFFFBB1C)
#define EIBD200                (*(volatile unsigned long  *)0xFFFFBB20)
#define EIBD201                (*(volatile unsigned long  *)0xFFFFBB24)
#define EIBD202                (*(volatile unsigned long  *)0xFFFFBB28)
#define EIBD203                (*(volatile unsigned long  *)0xFFFFBB2C)
#define EIBD204                (*(volatile unsigned long  *)0xFFFFBB30)
#define EIBD205                (*(volatile unsigned long  *)0xFFFFBB34)
#define EIBD206                (*(volatile unsigned long  *)0xFFFFBB38)
#define EIBD207                (*(volatile unsigned long  *)0xFFFFBB3C)
#define EIBD208                (*(volatile unsigned long  *)0xFFFFBB40)
#define EIBD209                (*(volatile unsigned long  *)0xFFFFBB44)
#define EIBD210                (*(volatile unsigned long  *)0xFFFFBB48)
#define EIBD211                (*(volatile unsigned long  *)0xFFFFBB4C)
#define EIBD212                (*(volatile unsigned long  *)0xFFFFBB50)
#define EIBD213                (*(volatile unsigned long  *)0xFFFFBB54)
#define EIBD214                (*(volatile unsigned long  *)0xFFFFBB58)
#define EIBD215                (*(volatile unsigned long  *)0xFFFFBB5C)
#define EIBD216                (*(volatile unsigned long  *)0xFFFFBB60)
#define EIBD217                (*(volatile unsigned long  *)0xFFFFBB64)
#define EIBD218                (*(volatile unsigned long  *)0xFFFFBB68)
#define EIBD219                (*(volatile unsigned long  *)0xFFFFBB6C)
#define EIBD220                (*(volatile unsigned long  *)0xFFFFBB70)
#define EIBD221                (*(volatile unsigned long  *)0xFFFFBB74)
#define EIBD222                (*(volatile unsigned long  *)0xFFFFBB78)
#define EIBD223                (*(volatile unsigned long  *)0xFFFFBB7C)
#define EIBD224                (*(volatile unsigned long  *)0xFFFFBB80)
#define EIBD225                (*(volatile unsigned long  *)0xFFFFBB84)
#define EIBD226                (*(volatile unsigned long  *)0xFFFFBB88)
#define EIBD227                (*(volatile unsigned long  *)0xFFFFBB8C)
#define EIBD228                (*(volatile unsigned long  *)0xFFFFBB90)
#define EIBD229                (*(volatile unsigned long  *)0xFFFFBB94)
#define EIBD230                (*(volatile unsigned long  *)0xFFFFBB98)
#define EIBD231                (*(volatile unsigned long  *)0xFFFFBB9C)
#define EIBD232                (*(volatile unsigned long  *)0xFFFFBBA0)
#define EIBD233                (*(volatile unsigned long  *)0xFFFFBBA4)
#define EIBD234                (*(volatile unsigned long  *)0xFFFFBBA8)
#define EIBD235                (*(volatile unsigned long  *)0xFFFFBBAC)
#define EIBD236                (*(volatile unsigned long  *)0xFFFFBBB0)
#define EIBD237                (*(volatile unsigned long  *)0xFFFFBBB4)
#define EIBD238                (*(volatile unsigned long  *)0xFFFFBBB8)
#define EIBD239                (*(volatile unsigned long  *)0xFFFFBBBC)
#define EIBD240                (*(volatile unsigned long  *)0xFFFFBBC0)
#define EIBD241                (*(volatile unsigned long  *)0xFFFFBBC4)
#define EIBD242                (*(volatile unsigned long  *)0xFFFFBBC8)
#define EIBD243                (*(volatile unsigned long  *)0xFFFFBBCC)
#define EIBD244                (*(volatile unsigned long  *)0xFFFFBBD0)
#define EIBD245                (*(volatile unsigned long  *)0xFFFFBBD4)
#define EIBD246                (*(volatile unsigned long  *)0xFFFFBBD8)
#define EIBD247                (*(volatile unsigned long  *)0xFFFFBBDC)
#define EIBD248                (*(volatile unsigned long  *)0xFFFFBBE0)
#define EIBD249                (*(volatile unsigned long  *)0xFFFFBBE4)
#define EIBD250                (*(volatile unsigned long  *)0xFFFFBBE8)
#define EIBD251                (*(volatile unsigned long  *)0xFFFFBBEC)
#define EIBD252                (*(volatile unsigned long  *)0xFFFFBBF0)
#define EIBD253                (*(volatile unsigned long  *)0xFFFFBBF4)
#define EIBD254                (*(volatile unsigned long  *)0xFFFFBBF8)
#define EIBD255                (*(volatile unsigned long  *)0xFFFFBBFC)
#define EIBD256                (*(volatile unsigned long  *)0xFFFFBC00)
#define EIBD257                (*(volatile unsigned long  *)0xFFFFBC04)
#define EIBD258                (*(volatile unsigned long  *)0xFFFFBC08)
#define EIBD259                (*(volatile unsigned long  *)0xFFFFBC0C)
#define EIBD260                (*(volatile unsigned long  *)0xFFFFBC10)
#define EIBD261                (*(volatile unsigned long  *)0xFFFFBC14)
#define EIBD262                (*(volatile unsigned long  *)0xFFFFBC18)
#define EIBD263                (*(volatile unsigned long  *)0xFFFFBC1C)
#define EIBD264                (*(volatile unsigned long  *)0xFFFFBC20)
#define EIBD265                (*(volatile unsigned long  *)0xFFFFBC24)
#define EIBD266                (*(volatile unsigned long  *)0xFFFFBC28)
#define EIBD267                (*(volatile unsigned long  *)0xFFFFBC2C)
#define EIBD268                (*(volatile unsigned long  *)0xFFFFBC30)
#define EIBD269                (*(volatile unsigned long  *)0xFFFFBC34)
#define EIBD270                (*(volatile unsigned long  *)0xFFFFBC38)
#define EIBD271                (*(volatile unsigned long  *)0xFFFFBC3C)
#define EIBD272                (*(volatile unsigned long  *)0xFFFFBC40)
#define EIBD273                (*(volatile unsigned long  *)0xFFFFBC44)                         
#define EIBD274                (*(volatile unsigned long  *)0xFFFFBC48)                                                                    
#define EIBD275                (*(volatile unsigned long  *)0xFFFFBC4C)
#define EIBD276                (*(volatile unsigned long  *)0xFFFFBC50)
#define EIBD277                (*(volatile unsigned long  *)0xFFFFBC54)
#define EIBD278                (*(volatile unsigned long  *)0xFFFFBC58)
#define EIBD279                (*(volatile unsigned long  *)0xFFFFBC5C)
#define EIBD280                (*(volatile unsigned long  *)0xFFFFBC60)
#define EIBD281                (*(volatile unsigned long  *)0xFFFFBC64)
#define EIBD282                (*(volatile unsigned long  *)0xFFFFBC68)
#define EIBD283                (*(volatile unsigned long  *)0xFFFFBC6C)
#define EIBD284                (*(volatile unsigned long  *)0xFFFFBC70)
#define EIBD285                (*(volatile unsigned long  *)0xFFFFBC74)
#define EIBD286                (*(volatile unsigned long  *)0xFFFFBC78)
#define EIBD287                (*(volatile unsigned long  *)0xFFFFBC7C)
#define EIBD288                (*(volatile unsigned long  *)0xFFFFBC80)
#define EIBD289                (*(volatile unsigned long  *)0xFFFFBC84)
#define EIBD290                (*(volatile unsigned long  *)0xFFFFBC88)
#define EIBD291                (*(volatile unsigned long  *)0xFFFFBC8C)
#define EIBD292                (*(volatile unsigned long  *)0xFFFFBC90)
#define EIBD293                (*(volatile unsigned long  *)0xFFFFBC94)
#define EIBD294                (*(volatile unsigned long  *)0xFFFFBC98)
#define EIBD295                (*(volatile unsigned long  *)0xFFFFBC9C)
#define EIBD296                (*(volatile unsigned long  *)0xFFFFBCA0)
#define EIBD297                (*(volatile unsigned long  *)0xFFFFBCA4)
#define EIBD298                (*(volatile unsigned long  *)0xFFFFBCA8)
#define EIBD299                (*(volatile unsigned long  *)0xFFFFBCAC)
#define EIBD300                (*(volatile unsigned long  *)0xFFFFBCB0)
#define EIBD301                (*(volatile unsigned long  *)0xFFFFBCB4)
#define EIBD302                (*(volatile unsigned long  *)0xFFFFBCB8)
#define EIBD303                (*(volatile unsigned long  *)0xFFFFBCBC)
#define EIBD304                (*(volatile unsigned long  *)0xFFFFBCC0)
#define EIBD305                (*(volatile unsigned long  *)0xFFFFBCC4)
#define EIBD306                (*(volatile unsigned long  *)0xFFFFBCC8)
#define EIBD307                (*(volatile unsigned long  *)0xFFFFBCCC)
#define EIBD308                (*(volatile unsigned long  *)0xFFFFBCD0)
#define EIBD309                (*(volatile unsigned long  *)0xFFFFBCD4)
#define EIBD310                (*(volatile unsigned long  *)0xFFFFBCD8)
#define EIBD311                (*(volatile unsigned long  *)0xFFFFBCDC)
#define EIBD312                (*(volatile unsigned long  *)0xFFFFBCE0)
#define EIBD313                (*(volatile unsigned long  *)0xFFFFBCE4)
#define EIBD314                (*(volatile unsigned long  *)0xFFFFBCE8)
#define EIBD315                (*(volatile unsigned long  *)0xFFFFBCEC)
#define EIBD316                (*(volatile unsigned long  *)0xFFFFBCF0)
#define EIBD317                (*(volatile unsigned long  *)0xFFFFBCF4)
#define EIBD318                (*(volatile unsigned long  *)0xFFFFBCF8)
#define EIBD319                (*(volatile unsigned long  *)0xFFFFBCFC)
#define EIBD320                (*(volatile unsigned long  *)0xFFFFBD00)
#define EIBD321                (*(volatile unsigned long  *)0xFFFFBD04)
#define EIBD322                (*(volatile unsigned long  *)0xFFFFBD08)
#define EIBD323                (*(volatile unsigned long  *)0xFFFFBD0C)
#define EIBD324                (*(volatile unsigned long  *)0xFFFFBD10)
#define EIBD325                (*(volatile unsigned long  *)0xFFFFBD14)
#define EIBD326                (*(volatile unsigned long  *)0xFFFFBD18)
#define EIBD327                (*(volatile unsigned long  *)0xFFFFBD1C)
#define EIBD328                (*(volatile unsigned long  *)0xFFFFBD20)
#define EIBD329                (*(volatile unsigned long  *)0xFFFFBD24)
#define EIBD330                (*(volatile unsigned long  *)0xFFFFBD28)
#define EIBD331                (*(volatile unsigned long  *)0xFFFFBD2C)
#define EIBD332                (*(volatile unsigned long  *)0xFFFFBD30)
#define EIBD333                (*(volatile unsigned long  *)0xFFFFBD34)
#define EIBD334                (*(volatile unsigned long  *)0xFFFFBD38)
#define EIBD335                (*(volatile unsigned long  *)0xFFFFBD3C)
#define EIBD336                (*(volatile unsigned long  *)0xFFFFBD40)
#define EIBD337                (*(volatile unsigned long  *)0xFFFFBD44)
#define EIBD338                (*(volatile unsigned long  *)0xFFFFBD48)
#define EIBD339                (*(volatile unsigned long  *)0xFFFFBD4C)
#define EIBD340                (*(volatile unsigned long  *)0xFFFFBD50)
#define EIBD341                (*(volatile unsigned long  *)0xFFFFBD54)
#define EIBD342                (*(volatile unsigned long  *)0xFFFFBD58)
#define EIBD343                (*(volatile unsigned long  *)0xFFFFBD5C)
#define EIBD344                (*(volatile unsigned long  *)0xFFFFBD60)
#define EIBD345                (*(volatile unsigned long  *)0xFFFFBD64)
#define EIBD346                (*(volatile unsigned long  *)0xFFFFBD68)
#define EIBD347                (*(volatile unsigned long  *)0xFFFFBD6C)
#define EIBD348                (*(volatile unsigned long  *)0xFFFFBD70)
#define EIBD349                (*(volatile unsigned long  *)0xFFFFBD74)
#define EIBD350                (*(volatile unsigned long  *)0xFFFFBD78)
#define EIBD351                (*(volatile unsigned long  *)0xFFFFBD7C)
#define EIBD352                (*(volatile unsigned long  *)0xFFFFBD80)
#define EIBD353                (*(volatile unsigned long  *)0xFFFFBD84)
#define EIBD354                (*(volatile unsigned long  *)0xFFFFBD88)
#define EIBD355                (*(volatile unsigned long  *)0xFFFFBD8C)
#define EIBD356                (*(volatile unsigned long  *)0xFFFFBD90)
#define EIBD357                (*(volatile unsigned long  *)0xFFFFBD94)
#define EIBD358                (*(volatile unsigned long  *)0xFFFFBD98)
#define EIBD359                (*(volatile unsigned long  *)0xFFFFBD9C)
#define EIBD360                (*(volatile unsigned long  *)0xFFFFBDA0)
#define EIBD361                (*(volatile unsigned long  *)0xFFFFBDA4)
#define EIBD362                (*(volatile unsigned long  *)0xFFFFBDA8)
#define EIBD363                (*(volatile unsigned long  *)0xFFFFBDAC)
#define EIBD364                (*(volatile unsigned long  *)0xFFFFBDB0)
#define EIBD365                (*(volatile unsigned long  *)0xFFFFBDB4)
#define EIBD366                (*(volatile unsigned long  *)0xFFFFBDB8)
#define EIBD367                (*(volatile unsigned long  *)0xFFFFBDBC)
#define EIBD368                (*(volatile unsigned long  *)0xFFFFBDC0)
#define EIBD369                (*(volatile unsigned long  *)0xFFFFBDC4)
#define EIBD370                (*(volatile unsigned long  *)0xFFFFBDC8)
#define EIBD371                (*(volatile unsigned long  *)0xFFFFBDCC)
#define EIBD372                (*(volatile unsigned long  *)0xFFFFBDD0)
#define EIBD373                (*(volatile unsigned long  *)0xFFFFBDD4)
#define EIBD374                (*(volatile unsigned long  *)0xFFFFBDD8)
#define EIBD375                (*(volatile unsigned long  *)0xFFFFBDDC)
#define EIBD376                (*(volatile unsigned long  *)0xFFFFBDE0)
#define EIBD377                (*(volatile unsigned long  *)0xFFFFBDE4)
#define EIBD378                (*(volatile unsigned long  *)0xFFFFBDE8)
#define EIBD379                (*(volatile unsigned long  *)0xFFFFBDEC)
#define EIBD380                (*(volatile unsigned long  *)0xFFFFBDF0)
#define EIBD381                (*(volatile unsigned long  *)0xFFFFBDF4)
#define EIBD382                (*(volatile unsigned long  *)0xFFFFBDF8)
#define EIBD383                (*(volatile unsigned long  *)0xFFFFBDFC)
#define EIBD384                (*(volatile unsigned long  *)0xFFFFBE00)
#define EIBD385                (*(volatile unsigned long  *)0xFFFFBE04)
#define EIBD386                (*(volatile unsigned long  *)0xFFFFBE08)
#define EIBD387                (*(volatile unsigned long  *)0xFFFFBE0C)
#define EIBD388                (*(volatile unsigned long  *)0xFFFFBE10)
#define EIBD389                (*(volatile unsigned long  *)0xFFFFBE14)
#define EIBD390                (*(volatile unsigned long  *)0xFFFFBE18)
#define EIBD391                (*(volatile unsigned long  *)0xFFFFBE1C)
#define EIBD392                (*(volatile unsigned long  *)0xFFFFBE20)
#define EIBD393                (*(volatile unsigned long  *)0xFFFFBE24)
#define EIBD394                (*(volatile unsigned long  *)0xFFFFBE28)
#define EIBD395                (*(volatile unsigned long  *)0xFFFFBE2C)
#define EIBD396                (*(volatile unsigned long  *)0xFFFFBE30)
#define EIBD397                (*(volatile unsigned long  *)0xFFFFBE34)
#define EIBD398                (*(volatile unsigned long  *)0xFFFFBE38)
#define EIBD399                (*(volatile unsigned long  *)0xFFFFBE3C)
#define EIBD400                (*(volatile unsigned long  *)0xFFFFBE40)
#define EIBD401                (*(volatile unsigned long  *)0xFFFFBE44)
#define EIBD402                (*(volatile unsigned long  *)0xFFFFBE48)
#define EIBD403                (*(volatile unsigned long  *)0xFFFFBE4C)
#define EIBD404                (*(volatile unsigned long  *)0xFFFFBE50)
#define EIBD405                (*(volatile unsigned long  *)0xFFFFBE54)
#define EIBD406                (*(volatile unsigned long  *)0xFFFFBE58)
#define EIBD407                (*(volatile unsigned long  *)0xFFFFBE5C)
#define EIBD408                (*(volatile unsigned long  *)0xFFFFBE60)
#define EIBD409                (*(volatile unsigned long  *)0xFFFFBE64)
#define EIBD410                (*(volatile unsigned long  *)0xFFFFBE68)
#define EIBD411                (*(volatile unsigned long  *)0xFFFFBE6C)
#define EIBD412                (*(volatile unsigned long  *)0xFFFFBE70)
#define EIBD413                (*(volatile unsigned long  *)0xFFFFBE74)
#define EIBD414                (*(volatile unsigned long  *)0xFFFFBE78)
#define EIBD415                (*(volatile unsigned long  *)0xFFFFBE7C)
#define EIBD416                (*(volatile unsigned long  *)0xFFFFBE80)
#define EIBD417                (*(volatile unsigned long  *)0xFFFFBE84)
#define EIBD418                (*(volatile unsigned long  *)0xFFFFBE88)
#define EIBD419                (*(volatile unsigned long  *)0xFFFFBE8C)
#define EIBD420                (*(volatile unsigned long  *)0xFFFFBE90)
#define EIBD421                (*(volatile unsigned long  *)0xFFFFBE94)
#define EIBD422                (*(volatile unsigned long  *)0xFFFFBE98)
#define EIBD423                (*(volatile unsigned long  *)0xFFFFBE9C)
#define EIBD424                (*(volatile unsigned long  *)0xFFFFBEA0)
#define EIBD425                (*(volatile unsigned long  *)0xFFFFBEA4)
#define EIBD426                (*(volatile unsigned long  *)0xFFFFBEA8)
#define EIBD427                (*(volatile unsigned long  *)0xFFFFBEAC)
#define EIBD428                (*(volatile unsigned long  *)0xFFFFBEB0)
#define EIBD429                (*(volatile unsigned long  *)0xFFFFBEB4)
#define EIBD430                (*(volatile unsigned long  *)0xFFFFBEB8)
#define EIBD431                (*(volatile unsigned long  *)0xFFFFBEBC)   
#define EIBD432                (*(volatile unsigned long  *)0xFFFFBEC0)
#define EIBD433                (*(volatile unsigned long  *)0xFFFFBEC4)
#define EIBD434                (*(volatile unsigned long  *)0xFFFFBEC8)
#define EIBD435                (*(volatile unsigned long  *)0xFFFFBECC)
#define EIBD436                (*(volatile unsigned long  *)0xFFFFBED0)
#define EIBD437                (*(volatile unsigned long  *)0xFFFFBED4)
#define EIBD438                (*(volatile unsigned long  *)0xFFFFBED8)
#define EIBD439                (*(volatile unsigned long  *)0xFFFFBEDC)
#define EIBD440                (*(volatile unsigned long  *)0xFFFFBEE0)
#define EIBD441                (*(volatile unsigned long  *)0xFFFFBEE4)
#define EIBD442                (*(volatile unsigned long  *)0xFFFFBEE8)
#define EIBD443                (*(volatile unsigned long  *)0xFFFFBEEC)
#define EIBD444                (*(volatile unsigned long  *)0xFFFFBEF0)
#define EIBD445                (*(volatile unsigned long  *)0xFFFFBEF4)
#define EIBD446                (*(volatile unsigned long  *)0xFFFFBEF8)
#define EIBD447                (*(volatile unsigned long  *)0xFFFFBEFC)
#define EIBD448                (*(volatile unsigned long  *)0xFFFFBF00)
#define EIBD449                (*(volatile unsigned long  *)0xFFFFBF04)
#define EIBD450                (*(volatile unsigned long  *)0xFFFFBF08)
#define EIBD451                (*(volatile unsigned long  *)0xFFFFBF0C)
#define EIBD452                (*(volatile unsigned long  *)0xFFFFBF10)
#define EIBD453                (*(volatile unsigned long  *)0xFFFFBF14)
#define EIBD454                (*(volatile unsigned long  *)0xFFFFBF18)
#define EIBD455                (*(volatile unsigned long  *)0xFFFFBF1C)
#define EIBD456                (*(volatile unsigned long  *)0xFFFFBF20)
#define EIBD457                (*(volatile unsigned long  *)0xFFFFBF24)
#define EIBD458                (*(volatile unsigned long  *)0xFFFFBF28)
#define EIBD459                (*(volatile unsigned long  *)0xFFFFBF2C)
#define EIBD460                (*(volatile unsigned long  *)0xFFFFBF30)
#define EIBD461                (*(volatile unsigned long  *)0xFFFFBF34)
#define EIBD462                (*(volatile unsigned long  *)0xFFFFBF38)
#define EIBD463                (*(volatile unsigned long  *)0xFFFFBF3C)
#define EIBD464                (*(volatile unsigned long  *)0xFFFFBF40)
#define EIBD465                (*(volatile unsigned long  *)0xFFFFBF44)
#define EIBD466                (*(volatile unsigned long  *)0xFFFFBF48)
#define EIBD467                (*(volatile unsigned long  *)0xFFFFBF4C)
#define EIBD468                (*(volatile unsigned long  *)0xFFFFBF50)
#define EIBD469                (*(volatile unsigned long  *)0xFFFFBF54)
#define EIBD470                (*(volatile unsigned long  *)0xFFFFBF58)
#define EIBD471                (*(volatile unsigned long  *)0xFFFFBF5C)
#define EIBD472                (*(volatile unsigned long  *)0xFFFFBF60)
#define EIBD473                (*(volatile unsigned long  *)0xFFFFBF64)
#define EIBD474                (*(volatile unsigned long  *)0xFFFFBF68)
#define EIBD475                (*(volatile unsigned long  *)0xFFFFBF6C)
#define EIBD476                (*(volatile unsigned long  *)0xFFFFBF70)
#define EIBD477                (*(volatile unsigned long  *)0xFFFFBF74)
#define EIBD478                (*(volatile unsigned long  *)0xFFFFBF78)
#define EIBD479                (*(volatile unsigned long  *)0xFFFFBF7C)
#define EIBD480                (*(volatile unsigned long  *)0xFFFFBF80)
#define EIBD481                (*(volatile unsigned long  *)0xFFFFBF84)
#define EIBD482                (*(volatile unsigned long  *)0xFFFFBF88)
#define EIBD483                (*(volatile unsigned long  *)0xFFFFBF8C)
#define EIBD484                (*(volatile unsigned long  *)0xFFFFBF90)
#define EIBD485                (*(volatile unsigned long  *)0xFFFFBF94)
#define EIBD486                (*(volatile unsigned long  *)0xFFFFBF98)
#define EIBD487                (*(volatile unsigned long  *)0xFFFFBF9C)
#define EIBD488                (*(volatile unsigned long  *)0xFFFFBFA0)
#define EIBD489                (*(volatile unsigned long  *)0xFFFFBFA4)
#define EIBD490                (*(volatile unsigned long  *)0xFFFFBFA8)
#define EIBD491                (*(volatile unsigned long  *)0xFFFFBFAC)
#define EIBD492                (*(volatile unsigned long  *)0xFFFFBFB0)
#define EIBD493                (*(volatile unsigned long  *)0xFFFFBFB4)
#define EIBD494                (*(volatile unsigned long  *)0xFFFFBFB8)
#define EIBD495                (*(volatile unsigned long  *)0xFFFFBFBC)
#define EIBD496                (*(volatile unsigned long  *)0xFFFFBFC0)
#define EIBD497                (*(volatile unsigned long  *)0xFFFFBFC4)
#define EIBD498                (*(volatile unsigned long  *)0xFFFFBFC8)
#define EIBD499                (*(volatile unsigned long  *)0xFFFFBFCC)
#define EIBD500                (*(volatile unsigned long  *)0xFFFFBFD0)
#define EIBD501                (*(volatile unsigned long  *)0xFFFFBFD4)
#define EIBD502                (*(volatile unsigned long  *)0xFFFFBFD8)
#define EIBD503                (*(volatile unsigned long  *)0xFFFFBFDC)
#define EIBD504                (*(volatile unsigned long  *)0xFFFFBFE0)
#define EIBD505                (*(volatile unsigned long  *)0xFFFFBFE4)
#define EIBD506                (*(volatile unsigned long  *)0xFFFFBFE8)
#define EIBD507                (*(volatile unsigned long  *)0xFFFFBFEC)
#define EIBD508                (*(volatile unsigned long  *)0xFFFFBFF0)
#define EIBD509                (*(volatile unsigned long  *)0xFFFFBFF4)
#define EIBD510                (*(volatile unsigned long  *)0xFFFFBFF8)
#define EIBD511                (*(volatile unsigned long  *)0xFFFFBFFC)

#define PFSSIMR0                  (*(volatile unsigned long  *)0xfffeeaf0ul)
/* ---- CAN interrupt controller registers ---- */
/* ERROR address of ICRXXX in English version HWM:
 *    r01uh0445ej0010_rh850f1h
 * Please refer right definition in Japanese version HWM:
 *    r01uh0445jj0011_rh850f1h   */
#if 1
#define REG_ICRCANGERR0               		(*(volatile uint16_t*)0xFFFEEA2CUL)
#define REG_ICRCANGRECC0              		(*(volatile uint16_t*)0xFFFEEA2CUL)
#define REG_ICRCAN0ERR                		(*(volatile uint16_t*)0xFFFEEA30UL)
#define REG_ICRCAN0REC                		(*(volatile uint16_t*)0xFFFEEA32UL)
#define REG_ICRCAN0TRX                		(*(volatile uint16_t*)0xFFFEEA34UL)

#else
#define REG_ICRCANGERR0               		(*(volatile uint16_t*)0xFFFFB02CUL)
#define REG_ICRCANGRECC0              		(*(volatile uint16_t*)0xFFFFB02EUL)
#define REG_ICRCAN0ERR                		(*(volatile uint16_t*)0xFFFFB030UL)
#define REG_ICRCAN0REC                		(*(volatile uint16_t*)0xFFFFB032UL)
#define REG_ICRCAN0TRX                		(*(volatile uint16_t*)0xFFFFB034UL)
#endif

#define REG_ICRCAN1ERR                		(*(volatile uint16_t*)0xFFFFB0E2UL)
#define REG_ICRCAN1REC                		(*(volatile uint16_t*)0xFFFFB0E4UL)
#define REG_ICRCAN1TRX                		(*(volatile uint16_t*)0xFFFFB0E6UL)
#define REG_ICRCAN2ERR                		(*(volatile uint16_t*)0xFFFFB1B2UL)
#define REG_ICRCAN2REC                		(*(volatile uint16_t*)0xFFFFB1B4UL)
#define REG_ICRCAN2TRX                		(*(volatile uint16_t*)0xFFFFB1B6UL)
#define REG_ICRCAN3ERR                		(*(volatile uint16_t*)0xFFFFB1B8UL)
#define REG_ICRCAN3REC                		(*(volatile uint16_t*)0xFFFFB1BAUL)
#define REG_ICRCAN3TRX                		(*(volatile uint16_t*)0xFFFFB1BCUL)
#define REG_ICRCAN4ERR                		(*(volatile uint16_t*)0xFFFFB220UL)
#define REG_ICRCAN4REC                		(*(volatile uint16_t*)0xFFFFB222UL)
#define REG_ICRCAN4TRX                		(*(volatile uint16_t*)0xFFFFB224UL)
#define REG_ICRCAN5ERR                		(*(volatile uint16_t*)0xFFFFB23EUL)
#define REG_ICRCAN5REC                		(*(volatile uint16_t*)0xFFFFB240UL)
#define REG_ICRCAN5TRX                		(*(volatile uint16_t*)0xFFFFB242UL)
#define REG_ICRCANGERR1               		(*(volatile uint16_t*)0xFFFFB27EUL)
#define REG_ICRCANGRECC1              		(*(volatile uint16_t*)0xFFFFB280UL)
#define REG_ICRCAN6ERR                		(*(volatile uint16_t*)0xFFFFB282UL)
#define REG_ICRCAN6REC                		(*(volatile uint16_t*)0xFFFFB284UL)
#define REG_ICRCAN6TRX                		(*(volatile uint16_t*)0xFFFFB286UL)

/* ---- LIN interrupt controller registers ---- */
#define REG_ICRLIN30                		(*(volatile uint16_t*)0xFFFFB042UL)
#define REG_ICRLIN30UR0                		(*(volatile uint16_t*)0xFFFFB044UL)
#define REG_ICRLIN30UR1                		(*(volatile uint16_t*)0xFFFFB046UL)
#define REG_ICRLIN30UR2                		(*(volatile uint16_t*)0xFFFFB048UL)
#define REG_ICRLIN20                		(*(volatile uint16_t*)0xFFFFB074UL)
#define REG_ICRLIN21                		(*(volatile uint16_t*)0xFFFFB076UL)
#define REG_ICRLIN31                		(*(volatile uint16_t*)0xFFFFB0F0UL)
#define REG_ICRLIN31UR0                		(*(volatile uint16_t*)0xFFFFB0F2UL)
#define REG_ICRLIN31UR1                		(*(volatile uint16_t*)0xFFFFB0F4UL)
#define REG_ICRLIN31UR2                		(*(volatile uint16_t*)0xFFFFB0F6UL)
#define REG_ICRLIN22                		(*(volatile uint16_t*)0xFFFFB144UL)
#define REG_ICRLIN23                		(*(volatile uint16_t*)0xFFFFB146UL)
#define REG_ICRLIN32                		(*(volatile uint16_t*)0xFFFFB148UL)
#define REG_ICRLIN32UR0                		(*(volatile uint16_t*)0xFFFFB14AUL)
#define REG_ICRLIN32UR1                		(*(volatile uint16_t*)0xFFFFB14CUL)
#define REG_ICRLIN32UR2                		(*(volatile uint16_t*)0xFFFFB14EUL)
#define REG_ICRLIN24                		(*(volatile uint16_t*)0xFFFFB1C4UL)
#define REG_ICRLIN25                		(*(volatile uint16_t*)0xFFFFB1C6UL)
#define REG_ICRLIN33                		(*(volatile uint16_t*)0xFFFFB1C8UL)
#define REG_ICRLIN33UR0                		(*(volatile uint16_t*)0xFFFFB1CAUL)
#define REG_ICRLIN33UR1                		(*(volatile uint16_t*)0xFFFFB1CCUL)
#define REG_ICRLIN33UR2                		(*(volatile uint16_t*)0xFFFFB1CEUL)
#define REG_ICRLIN34                		(*(volatile uint16_t*)0xFFFFB1D0UL)
#define REG_ICRLIN34UR0                		(*(volatile uint16_t*)0xFFFFB1D2UL)
#define REG_ICRLIN34UR1                		(*(volatile uint16_t*)0xFFFFB1D4UL)
#define REG_ICRLIN34UR2                		(*(volatile uint16_t*)0xFFFFB1D6UL)
#define REG_ICRLIN35                		(*(volatile uint16_t*)0xFFFFB1D8UL)
#define REG_ICRLIN35UR0                		(*(volatile uint16_t*)0xFFFFB1DAUL)
#define REG_ICRLIN35UR1                		(*(volatile uint16_t*)0xFFFFB1DCUL)
#define REG_ICRLIN35UR2                		(*(volatile uint16_t*)0xFFFFB1DEUL)
#define REG_ICRLIN26                		(*(volatile uint16_t*)0xFFFFB226UL)
#define REG_ICRLIN27                		(*(volatile uint16_t*)0xFFFFB228UL)
#define REG_ICRLIN28                		(*(volatile uint16_t*)0xFFFFB23AUL)
#define REG_ICRLIN29                		(*(volatile uint16_t*)0xFFFFB23CUL)
#define REG_ICRLIN210                		(*(volatile uint16_t*)0xFFFFB288UL)
#define REG_ICRLIN211                		(*(volatile uint16_t*)0xFFFFB28AUL)

/* ---- FLX interrupt controller registers ---- */
#define REG_ICFLX0FDA                		(*(volatile uint16_t*)0xFFFFB15AUL)
#define REG_ICFLX0FW                		(*(volatile uint16_t*)0xFFFFB15CUL)
#define REG_ICFLX0IQE                		(*(volatile uint16_t*)0xFFFFB15EUL)
#define REG_ICFLX0IQF                		(*(volatile uint16_t*)0xFFFFB160UL)
#define REG_ICFLX0OW                		(*(volatile uint16_t*)0xFFFFB162UL)
#define REG_ICFLX0OT                		(*(volatile uint16_t*)0xFFFFB164UL)
#define REG_ICFLX0LINE0                		(*(volatile uint16_t*)0xFFFFB166UL)
#define REG_ICFLX0LINE1                		(*(volatile uint16_t*)0xFFFFB168UL)
#define REG_ICFLX0TIM0                		(*(volatile uint16_t*)0xFFFFB16AUL)
#define REG_ICFLX0TIM1                		(*(volatile uint16_t*)0xFFFFB16CUL)
#define REG_ICFLX0TIM2                		(*(volatile uint16_t*)0xFFFFB16EUL)

/* ---- Eth interrupt controller registers ---- */
#define REG_ICETNB0DATA                		(*(volatile uint16_t*)0xFFFFB276UL)
#define REG_ETH1                			(*(volatile uint16_t*)0xFFFFB278UL)
#define REG_ETH2                			(*(volatile uint16_t*)0xFFFFB27AUL)
#define REG_ETH3                			(*(volatile uint16_t*)0xFFFFB27CUL)
#endif
